spring.application.name=KFS-MatchEntry

########## コンテキストパス設定 ##########
server.servlet.context-path=/KFS-MatchEntry

########## データベース設定 ##########
# ドライバ名
spring.datasource.driver-class-name=org.postgresql.Driver
# JDBC URL
spring.datasource.url=jdbc:postgresql://localhost:5432/frodb

# ユーザー名
spring.datasource.username=frouser
# パスワード
spring.datasource.password=frouser